# Generated by Django 4.2.11 on 2024-05-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('catagory', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('adoption_status', models.CharField(choices=[('pending', 'pending'), ('adopted', 'adopted')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Pets/')),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shelters.shelter')),
            ],
        ),
    ]
