# Generated by Django 4.2.11 on 2024-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0003_alter_pet_adoption_status_alter_pet_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('available', 'available'), ('adopted', 'adopted')], default='adopted', max_length=10),
        ),
    ]
