# Generated by Django 4.2.11 on 2024-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0004_rename_catagory_pet_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
