# Generated by Django 4.2.11 on 2024-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
