# Generated by Django 4.2.11 on 2024-05-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pets', '0001_initial'),
        ('Adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopting_pet', to='Pets.pet'),
        ),
    ]
